### ISSUE TITLE
Using lower bound on base instead of conditionals to guard against older versions of GHC

### ISSUE THREAD

**Issue by sol** [vincenthz/haskell-pkg-guidelines#2]
For what reason would I prefer

```yaml
when:
  - condition: "impl(ghc < 8.0)"
    then:
      buildable: False
    else:
      dependencies: base
```

over

```yaml
dependencies: base >= 4.9.0.0
```
?

(From my perspective conditionals are somewhat of a misfeature.  That is esp. true in combination with "automatic" flags, which turn the dependency solver into some sort of mini prolog).
